server:
  port: 8888
  servlet:
    context-path: /text
  tomcat:
    basedir: "" #上传文件临时目录
spring:
  profiles:
    active:
      - lst
      - value
#url访问图片的路径
      #logging:
#  level:
#    root: DEBUG
#  file: classpath:/log.log
#  redis:
#    host: 47.107.112.230
#    port: 6379
#    password: lstroot 
#    timeout: 10000 #客户端连接超时
#    jedis:
#      pool:
#        max-idle: 300 #最大空闲数
#        max-active: 600 #最大连接数 0无限制
#        max-wait: 1000 #最大连接等待时间 -1 无限制
        