server:
  port: 8080
  servlet:
    context-path: /oranth
  tomcat:
    basedir: temp

#logging:
#  level:
#    root: error
mybatisplus:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.oranth.applicationmarket.entity

spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署
  servlet:
    multipart:
      enabled: true  
      file-size-threshold: 0
      max-file-size: 1500MB #上传文件最大值
      max-request-size: 1500MB
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    mode: LEGACYHTML5 #LEGACYHTML5需要额外的库 # 因为HTML5很严格的检测
#    encoding: UTF-8
#    servlet:
#      content-type: text/html
#    cache: false #关闭缓存 查看实时页面

  mvc:
    static-path-pattern: /**
  resources:
    static-locations:
      - classpath:/META-INF/resources/
      - classpath:/resources/
      - classpath:/static/
      - classpath:/public/
      - classpath:/templates/
  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver   # com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/oranth_app_store?serverTimezone=UTC&characterEncoding=utf8&useSSL=true

    
  #      type: com.alibaba.druid.pool.DruidDataSource
  #      driver-class-name: com.mysql.jdbc.Driver
        
 # messages: #多语言支持
 #   basename: i18n/login/login,i18n/index/index
mybatis:
  configuration:
    lazy-loading-enabled: false  #全局性设置懒加载。如果设为‘false’，则所有相关联的都会被初始化加载。
    aggressive-lazy-loading: false #true时懒加载的对象可能被任何懒属性全部加载，否则，每个属性都按需加载
    cache-enabled: true #开启二级缓存
  mapper-locations: classpath:mapping/*.xml

#      type: com.alibaba.druid.pool.DruidDataSource
#      driver-class-name: com.mysql.jdbc.Driver
#  redis:
#    password: lstroot
#    timeout: 5000
#    database: 0
#    host: 47.107.112.230
#    port: 7001
#    cluster:
#      nodes:
#        - 47.107.112.230:7001
#        - 47.107.112.230:7002
#        - 47.107.112.230:7003
#        - 47.107.112.230:7004
#        - 47.107.112.230:7005
#        - 47.107.112.230:7006
#    jedis:
#      pool:
#        max-idle: 600
#        min-idle: 30
#        max-wait: 180000 #最大空闲时间毫秒 300000
#        max-active: 600 #最大链接数
  